import { ActivityCategory, Project, DayData } from '@/types';

export const CATEGORY_COLORS: Record<ActivityCategory, { bg: string; text: string; border: string; accent: string }> = {
  Reading: { bg: 'bg-amber-950/40', text: 'text-amber-300', border: 'border-amber-700/50', accent: '#f59e0b' },
  Coding: { bg: 'bg-emerald-950/40', text: 'text-emerald-300', border: 'border-emerald-700/50', accent: '#10b981' },
  'Deep Work': { bg: 'bg-indigo-950/40', text: 'text-indigo-300', border: 'border-indigo-700/50', accent: '#6366f1' },
  Learning: { bg: 'bg-cyan-950/40', text: 'text-cyan-300', border: 'border-cyan-700/50', accent: '#06b6d4' },
  Fitness: { bg: 'bg-rose-950/40', text: 'text-rose-300', border: 'border-rose-700/50', accent: '#f43f5e' },
  Mindfulness: { bg: 'bg-purple-950/40', text: 'text-purple-300', border: 'border-purple-700/50', accent: '#a855f7' },
  Personal: { bg: 'bg-blue-950/40', text: 'text-blue-300', border: 'border-blue-700/50', accent: '#3b82f6' },
  Rest: { bg: 'bg-slate-900/60', text: 'text-slate-400', border: 'border-slate-700/40', accent: '#64748b' },
};

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'Self-Development & Daily Reading',
    category: 'Reading',
    description: 'Read 25+ pages daily from high-impact psychology, habits, and philosophy books.',
    targetHours: 30,
    color: '#f59e0b',
    milestones: [
      { id: 'm1', title: 'Finish "Atomic Habits" by James Clear', completed: true },
      { id: 'm2', title: 'Complete "Deep Work" by Cal Newport', completed: false },
      { id: 'm3', title: 'Write summary notes in knowledge base', completed: false },
    ],
    createdAt: '2026-09-01',
  },
  {
    id: 'proj-2',
    title: 'ID2950 Application Engineering',
    category: 'Coding',
    description: 'Architect and expand ID2950 productivity system into personal life command center.',
    targetHours: 60,
    color: '#10b981',
    milestones: [
      { id: 'm4', title: 'Setup interactive timeline tracking', completed: true },
      { id: 'm5', title: 'Build Self-Development Project manager', completed: true },
      { id: 'm6', title: 'Integrate real-time Focus Pomodoro timer', completed: false },
    ],
    createdAt: '2026-09-15',
  },
  {
    id: 'proj-3',
    title: 'Peak Fitness & Daily Longevity',
    category: 'Fitness',
    description: 'Strength training, 10k daily steps, hydration, and recovery.',
    targetHours: 25,
    color: '#f43f5e',
    milestones: [
      { id: 'm7', title: '14-day consistent morning workout streak', completed: true },
      { id: 'm8', title: 'Drink 3+ liters of water daily', completed: false },
    ],
    createdAt: '2026-09-20',
  },
];

export const getInitialDayData = (dateStr: string): DayData => ({
  date: dateStr,
  priorities: [
    { id: 'p1', text: 'Morning Book Reading (Atomic Habits - Chapter 4)', completed: true },
    { id: 'p2', text: 'Build ID2950 Next.js Productivity Architecture', completed: false },
    { id: 'p3', text: '45-minute HIIT & Strength workout session', completed: true },
  ],
  reflection: {
    wins: 'Finished 30 pages of reading with deep focus and shipped core project module on time.',
    improvements: 'Avoid opening social media before the 10:00 block; keep water bottle filled at desk.',
    overallScore: 92,
    sleepHours: 7.5,
    waterGlasses: 8,
    mood: '⚡ Energized',
  },
  timeBlocks: [
    {
      id: 'tb-1',
      startTime: '06:30',
      endTime: '07:30',
      title: 'Morning Mobility & Workout',
      category: 'Fitness',
      projectId: 'proj-3',
      notes: 'Full body stretching, kettlebell circuits, and cold shower.',
      productivityRating: 5,
      completed: true,
    },
    {
      id: 'tb-2',
      startTime: '07:30',
      endTime: '08:30',
      title: 'Nutritious Breakfast & Day Planning',
      category: 'Personal',
      notes: 'Oatmeal, protein smoothie, reviewing daily top 3 priorities.',
      productivityRating: 4,
      completed: true,
    },
    {
      id: 'tb-3',
      startTime: '09:00',
      endTime: '10:00',
      title: 'Book reading',
      category: 'Reading',
      projectId: 'proj-1',
      notes: 'Reading "Atomic Habits" - The 4 Laws of Behavior Change. Took 3 pages of actionable notes.',
      productivityRating: 5,
      completed: true,
    },
    {
      id: 'tb-4',
      startTime: '10:15',
      endTime: '12:30',
      title: 'ID2950 Next.js Architecture & Coding',
      category: 'Coding',
      projectId: 'proj-2',
      notes: 'Built interactive time block manager, project progress tracking, and dynamic analytics.',
      productivityRating: 5,
      completed: true,
    },
    {
      id: 'tb-5',
      startTime: '12:30',
      endTime: '13:30',
      title: 'Healthy Lunch & Walking Break',
      category: 'Rest',
      notes: 'Clean whole-food meal and 20 min sunshine walk outside.',
      productivityRating: 4,
      completed: true,
    },
    {
      id: 'tb-6',
      startTime: '14:00',
      endTime: '16:00',
      title: 'Deep Work: System Design & Algorithms',
      category: 'Learning',
      notes: 'Distributed system patterns and microservice caching strategies.',
      productivityRating: 4,
      completed: false,
    },
    {
      id: 'tb-7',
      startTime: '16:30',
      endTime: '17:30',
      title: 'Review Day Progress & Self-Reflection',
      category: 'Mindfulness',
      notes: 'Documenting what worked well, calculating daily productivity score.',
      productivityRating: 5,
      completed: false,
    },
  ],
});

